version: '3.9'

services:
  web:
    container_name: auth-system
    image: auth-system:1.0.0
    build:  .
    ports:
      - "8081:8080"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=123456789
      - DB_URL=jdbc:mysql://db:3306/auth_system
    depends_on:
      - db
  db:
    container_name: auth-system-db
    image: mariadb:11.2.3
    environment:
      MARIADB_ROOT_PASSWORD: 123456789
      MARIADB_DATABASE: auth_system
    ports:
      - "3306:3306"
